public class TurkisLesson1 {
    public integer lenghtOfSentence(string text){
        integer x = text.length();
        return x;
    }

    public integer basamakSayisi(integer sayi){
        string y = string.valueOf(sayi);
        integer z = y.length();
        return z;
    }

    public integer add(integer x, integer y){
        integer sum = x+y;
        return sum;
    }

    public integer multi(integer a, integer b){
        integer result = a*b;
        return result;
    }

    
}
