TurkishLesson2.numberComparision(40, 40);
TurkishLesson2.numberComparision2(12, 50);
TurkishLesson2.numberComparision2(10, 10);
TurkishLesson2.marketAlisverisi('simit', 5);
TurkishLesson2.marketAlisverisi('ekmek', 10);
TurkishLesson2.marketAlisverisi('KEK', 4);
TurkishLesson2.marketAlisverisi('maydanoz', 2);
system.debug(TurkishLesson2.sum(10));
system.debug(TurkishLesson2.addString('Esranur', 10));